# Coolify Configuration for azeltech.midiya.az
# This file helps Coolify understand your application structure

version: '3.8'

services:
  azeltech-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: azeltech-app
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - VITE_API_URL=${VITE_API_URL}
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./public/cvs:/app/public/cvs
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

